name: Update X Content

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every hour
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-x-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Create X content
        run: node .github/scripts/generate-x-content.js
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add news-data.js
          git diff --quiet && git diff --staged --quiet || git commit -m "Update X content"
          git push
